# Generated by Django 4.2.1 on 2024-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone_1', models.CharField(max_length=15)),
                ('number_phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=64)),
                ('email_2', models.CharField(blank=True, max_length=64, null=True)),
                ('monday', models.CharField(blank=True, max_length=20, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=20, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=20, null=True)),
                ('thursday', models.CharField(blank=True, max_length=20, null=True)),
                ('friday', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('specialization', models.CharField(choices=[('lekarz rodziny', 'Lekarz rodziny'), ('pediatra', 'Pediatra'), ('pielęgniarka środowiskowa', 'Pielęgniarka środowiskowa')], max_length=50)),
                ('monday', models.CharField(blank=True, max_length=20, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=20, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=20, null=True)),
                ('thursday', models.CharField(blank=True, max_length=20, null=True)),
                ('friday', models.CharField(blank=True, max_length=20, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='doctor_files/')),
            ],
        ),
        migrations.CreateModel(
            name='File_to_download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodo', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('reglamin', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('doctor', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('nurse', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('calendar', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('application_for_authorisation', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='post_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Reglamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Rodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
