# Generated by Django 4.2.1 on 2024-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_to_download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodo', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('reglamin', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('doctor', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('nurse', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('calendar', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
                ('application_for_authorisation', models.FileField(blank=True, null=True, upload_to='files_to_download/')),
            ],
        ),
        migrations.CreateModel(
            name='Reglamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Rodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='number_phone',
            new_name='number_phone_1',
        ),
        migrations.AddField(
            model_name='contact',
            name='number_phone_2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='doctor_files/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='friday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='monday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='thursday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='tuesday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='wednesday',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
