# Generated by Django 4.2.1 on 2024-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_to_download_reglamin_rodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='friday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='monday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='thursday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tuesday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='wednesday',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
