# Generated by Django 4.2.1 on 2024-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact_email_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
